/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;
import org.sablecc.sablecc.analysis.*;

public final class ARegExp extends PRegExp
{
  private final LinkedList _concats_ = new TypedLinkedList(new Concats_Cast());

  public ARegExp()
  {}

  public ARegExp(
    List _concats_)
  {
    {
      this._concats_.clear();
      this._concats_.addAll(_concats_);
    }

  }
  public Object clone()
  {
    return new ARegExp(
             cloneList(_concats_));
  }

  public void apply(Switch sw)
  {
    ((Analysis) sw).caseARegExp(this);
  }

  public LinkedList getConcats()
  {
    return _concats_;
  }

  public void setConcats(List list)
  {
    _concats_.clear();
    _concats_.addAll(list);
  }

  public String toString()
  {
    return ""
           + toString(_concats_);
  }

  void removeChild(Node child)
  {
    if(_concats_.remove(child))
    {
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild)
  {
    for(ListIterator i = _concats_.listIterator(); i.hasNext();)
    {
      if(i.next() == oldChild)
      {
        if(newChild != null)
        {
          i.set(newChild);
          oldChild.parent(null);
          return;
        }

        i.remove();
        oldChild.parent(null);
        return;
      }
    }

  }

  private class Concats_Cast implements Cast
  {
    public Object cast(Object o)
    {
      PConcat node = (PConcat) o;

      if((node.parent() != null) &&
          (node.parent() != ARegExp.this))
      {
        node.parent().removeChild(node);
      }

      if((node.parent() == null) ||
          (node.parent() != ARegExp.this))
      {
        node.parent(ARegExp.this);
      }

      return node;
    }
  }
}
