/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import org.sablecc.sablecc.analysis.*;

public final class TTree extends Token
{
  public TTree()
  {
    super.setText("Tree");
  }

  public TTree(int line, int pos)
  {
    super.setText("Tree");
    setLine(line);
    setPos(pos);
  }

  public Object clone()
  {
    return new TTree(getLine(), getPos());
  }

  public void apply(Switch sw)
  {
    ((Analysis) sw).caseTTree(this);
  }

  public void setText(String text)
  {
    throw new RuntimeException("Cannot change TTree text.");
  }
}
