/** This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.node;

import org.trommel.trommel.scripting.analysis.*;

@SuppressWarnings("nls")
public final class AMaxFunction extends PFunction
{
    private TMax _max_;

    public AMaxFunction()
    {
        // Constructor
    }

    public AMaxFunction(
         TMax _max_)
    {
        // Constructor
        setMax(_max_);

    }

    @Override
    public Object clone()
    {
        return new AMaxFunction(
            cloneNode(this._max_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaxFunction(this);
    }

    public TMax getMax()
    {
        return this._max_;
    }

    public void setMax(TMax node)
    {
        if(this._max_ != null)
        {
            this._max_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._max_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._max_);
    }

    @Override
    void removeChild( Node child)
    {
        // Remove child
        if(this._max_ == child)
        {
            this._max_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild( Node oldChild,  Node newChild)
    {
        // Replace child
        if(this._max_ == oldChild)
        {
            setMax((TMax) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
