/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.node;

import org.trommel.trommel.scripting.analysis.*;

@SuppressWarnings("nls")
public final class AProfileDataTrommelScript extends PTrommelScript
{
    private PLoadDataStatement _loadDataStatement_;
    private PProfileDataStatement _profileDataStatement_;

    public AProfileDataTrommelScript()
    {
        // Constructor
    }

    public AProfileDataTrommelScript(
         PLoadDataStatement _loadDataStatement_,
         PProfileDataStatement _profileDataStatement_)
    {
        // Constructor
        setLoadDataStatement(_loadDataStatement_);

        setProfileDataStatement(_profileDataStatement_);

    }

    @Override
    public Object clone()
    {
        return new AProfileDataTrommelScript(
            cloneNode(this._loadDataStatement_),
            cloneNode(this._profileDataStatement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProfileDataTrommelScript(this);
    }

    public PLoadDataStatement getLoadDataStatement()
    {
        return this._loadDataStatement_;
    }

    public void setLoadDataStatement(PLoadDataStatement node)
    {
        if(this._loadDataStatement_ != null)
        {
            this._loadDataStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._loadDataStatement_ = node;
    }

    public PProfileDataStatement getProfileDataStatement()
    {
        return this._profileDataStatement_;
    }

    public void setProfileDataStatement(PProfileDataStatement node)
    {
        if(this._profileDataStatement_ != null)
        {
            this._profileDataStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._profileDataStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._loadDataStatement_)
            + toString(this._profileDataStatement_);
    }

    @Override
    void removeChild( Node child)
    {
        // Remove child
        if(this._loadDataStatement_ == child)
        {
            this._loadDataStatement_ = null;
            return;
        }

        if(this._profileDataStatement_ == child)
        {
            this._profileDataStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild( Node oldChild,  Node newChild)
    {
        // Replace child
        if(this._loadDataStatement_ == oldChild)
        {
            setLoadDataStatement((PLoadDataStatement) newChild);
            return;
        }

        if(this._profileDataStatement_ == oldChild)
        {
            setProfileDataStatement((PProfileDataStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
