/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.node;

import org.trommel.trommel.scripting.analysis.*;

@SuppressWarnings("nls")
public final class AReqFunction extends PFunction
{
    private TReq _req_;

    public AReqFunction()
    {
        // Constructor
    }

    public AReqFunction(
         TReq _req_)
    {
        // Constructor
        setReq(_req_);

    }

    @Override
    public Object clone()
    {
        return new AReqFunction(
            cloneNode(this._req_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReqFunction(this);
    }

    public TReq getReq()
    {
        return this._req_;
    }

    public void setReq(TReq node)
    {
        if(this._req_ != null)
        {
            this._req_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._req_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._req_);
    }

    @Override
    void removeChild( Node child)
    {
        // Remove child
        if(this._req_ == child)
        {
            this._req_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild( Node oldChild,  Node newChild)
    {
        // Replace child
        if(this._req_ == oldChild)
        {
            setReq((TReq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
