/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.node;

import org.trommel.trommel.scripting.analysis.*;

@SuppressWarnings("nls")
public final class ASingleProfiledFields extends PProfiledFields
{
    private PProfiledField _profiledField_;

    public ASingleProfiledFields()
    {
        // Constructor
    }

    public ASingleProfiledFields(
         PProfiledField _profiledField_)
    {
        // Constructor
        setProfiledField(_profiledField_);

    }

    @Override
    public Object clone()
    {
        return new ASingleProfiledFields(
            cloneNode(this._profiledField_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleProfiledFields(this);
    }

    public PProfiledField getProfiledField()
    {
        return this._profiledField_;
    }

    public void setProfiledField(PProfiledField node)
    {
        if(this._profiledField_ != null)
        {
            this._profiledField_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._profiledField_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._profiledField_);
    }

    @Override
    void removeChild( Node child)
    {
        // Remove child
        if(this._profiledField_ == child)
        {
            this._profiledField_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild( Node oldChild,  Node newChild)
    {
        // Replace child
        if(this._profiledField_ == oldChild)
        {
            setProfiledField((PProfiledField) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
