/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.node;

import org.trommel.trommel.scripting.analysis.*;

@SuppressWarnings("nls")
public final class TLeftParen extends Token
{
    public TLeftParen()
    {
        super.setText("(");
    }

    public TLeftParen(int line, int pos)
    {
        super.setText("(");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLeftParen(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLeftParen(this);
    }

    @Override
    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLeftParen text.");
    }
}
