/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.node;

import org.trommel.trommel.scripting.analysis.*;

@SuppressWarnings("nls")
public final class TPercent extends Token
{
    public TPercent()
    {
        super.setText("%");
    }

    public TPercent(int line, int pos)
    {
        super.setText("%");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPercent(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPercent(this);
    }

    @Override
    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPercent text.");
    }
}
