/** This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.parser;

import org.trommel.trommel.scripting.lexer.*;
import org.trommel.trommel.scripting.node.*;
import org.trommel.trommel.scripting.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings({"nls", "rawtypes"})
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser( Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    @SuppressWarnings("unchecked")
	private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AProfileDataTrommelScript */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AReportDataTrommelScript */
		    {
			ArrayList list = new1();
			push(goTo(0), list, false);
		    }
		    break;
                    case 2: /* reduce ASampleDataTrommelScript */
		    {
			ArrayList list = new2();
			push(goTo(0), list, false);
		    }
		    break;
                    case 3: /* reduce ALoadDataStatement */
		    {
			ArrayList list = new3();
			push(goTo(1), list, false);
		    }
		    break;
                    case 4: /* reduce ALoadedFile */
		    {
			ArrayList list = new4();
			push(goTo(2), list, false);
		    }
		    break;
                    case 5: /* reduce ALoadedFields */
		    {
			ArrayList list = new5();
			push(goTo(3), list, false);
		    }
		    break;
                    case 6: /* reduce ASingleFieldList */
		    {
			ArrayList list = new6();
			push(goTo(4), list, false);
		    }
		    break;
                    case 7: /* reduce AListFieldList */
		    {
			ArrayList list = new7();
			push(goTo(4), list, false);
		    }
		    break;
                    case 8: /* reduce AField */
		    {
			ArrayList list = new8();
			push(goTo(5), list, false);
		    }
		    break;
                    case 9: /* reduce ADefaultFieldsTerminatedBy */
		    {
			ArrayList list = new9();
			push(goTo(6), list, false);
		    }
		    break;
                    case 10: /* reduce ACustomFieldsTerminatedBy */
		    {
			ArrayList list = new10();
			push(goTo(6), list, false);
		    }
		    break;
                    case 11: /* reduce AFieldTerminator */
		    {
			ArrayList list = new11();
			push(goTo(7), list, false);
		    }
		    break;
                    case 12: /* reduce AProfileDataStatement */
		    {
			ArrayList list = new12();
			push(goTo(8), list, false);
		    }
		    break;
                    case 13: /* reduce ASingleProfiledFields */
		    {
			ArrayList list = new13();
			push(goTo(9), list, false);
		    }
		    break;
                    case 14: /* reduce AListProfiledFields */
		    {
			ArrayList list = new14();
			push(goTo(9), list, false);
		    }
		    break;
                    case 15: /* reduce AProfiledField */
		    {
			ArrayList list = new15();
			push(goTo(10), list, false);
		    }
		    break;
                    case 16: /* reduce AListProfilers */
		    {
			ArrayList list = new16();
			push(goTo(11), list, false);
		    }
		    break;
                    case 17: /* reduce AAllBuiltinProfilers */
		    {
			ArrayList list = new17();
			push(goTo(11), list, false);
		    }
		    break;
                    case 18: /* reduce ASingleFunctionList */
		    {
			ArrayList list = new18();
			push(goTo(12), list, false);
		    }
		    break;
                    case 19: /* reduce AListFunctionList */
		    {
			ArrayList list = new19();
			push(goTo(12), list, false);
		    }
		    break;
                    case 20: /* reduce AMaxFunction */
		    {
			ArrayList list = new20();
			push(goTo(13), list, false);
		    }
		    break;
                    case 21: /* reduce AMinFunction */
		    {
			ArrayList list = new21();
			push(goTo(13), list, false);
		    }
		    break;
                    case 22: /* reduce ADistinctFunction */
		    {
			ArrayList list = new22();
			push(goTo(13), list, false);
		    }
		    break;
                    case 23: /* reduce AEmptyFunction */
		    {
			ArrayList list = new23();
			push(goTo(13), list, false);
		    }
		    break;
                    case 24: /* reduce AReqFunction */
		    {
			ArrayList list = new24();
			push(goTo(13), list, false);
		    }
		    break;
                    case 25: /* reduce AVarFunction */
		    {
			ArrayList list = new25();
			push(goTo(13), list, false);
		    }
		    break;
                    case 26: /* reduce ALinFunction */
		    {
			ArrayList list = new26();
			push(goTo(13), list, false);
		    }
		    break;
                    case 27: /* reduce AConfFunction */
		    {
			ArrayList list = new27();
			push(goTo(13), list, false);
		    }
		    break;
                    case 28: /* reduce ADefaultLinearity */
		    {
			ArrayList list = new28();
			push(goTo(14), list, false);
		    }
		    break;
                    case 29: /* reduce ADefaultParenLinearity */
		    {
			ArrayList list = new29();
			push(goTo(14), list, false);
		    }
		    break;
                    case 30: /* reduce AParmLinearity */
		    {
			ArrayList list = new30();
			push(goTo(14), list, false);
		    }
		    break;
                    case 31: /* reduce ADefaultConfidence */
		    {
			ArrayList list = new31();
			push(goTo(15), list, false);
		    }
		    break;
                    case 32: /* reduce ADefaultParenConfidence */
		    {
			ArrayList list = new32();
			push(goTo(15), list, false);
		    }
		    break;
                    case 33: /* reduce AParmConfidence */
		    {
			ArrayList list = new33();
			push(goTo(15), list, false);
		    }
		    break;
                    case 34: /* reduce AReportDataStatement */
		    {
			ArrayList list = new34();
			push(goTo(16), list, false);
		    }
		    break;
                    case 35: /* reduce ASingleReportedFields */
		    {
			ArrayList list = new35();
			push(goTo(17), list, false);
		    }
		    break;
                    case 36: /* reduce AListReportedFields */
		    {
			ArrayList list = new36();
			push(goTo(17), list, false);
		    }
		    break;
                    case 37: /* reduce AReportedField */
		    {
			ArrayList list = new37();
			push(goTo(18), list, false);
		    }
		    break;
                    case 38: /* reduce ASampleDataStatement */
		    {
			ArrayList list = new38();
			push(goTo(19), list, false);
		    }
		    break;
                    case 39: /* reduce ASampledFile */
		    {
			ArrayList list = new39();
			push(goTo(20), list, false);
		    }
		    break;
                    case 40: /* reduce ASampleRate */
		    {
			ArrayList list = new40();
			push(goTo(21), list, false);
		    }
		    break;
                    case 41: /* reduce AStoreStorage */
		    {
			ArrayList list = new41();
			push(goTo(22), list, false);
		    }
		    break;
                    case 42: /* reduce AExportStorage */
		    {
			ArrayList list = new42();
			push(goTo(22), list, false);
		    }
		    break;
                    case 43: /* reduce AStoreExportStorage */
		    {
			ArrayList list = new43();
			push(goTo(22), list, false);
		    }
		    break;
                    case 44: /* reduce AExportStoreStorage */
		    {
			ArrayList list = new44();
			push(goTo(22), list, false);
		    }
		    break;
                    case 45: /* reduce AHdfsFilePath */
		    {
			ArrayList list = new45();
			push(goTo(23), list, false);
		    }
		    break;
                    case 46: /* reduce ALocalFilePath */
		    {
			ArrayList list = new46();
			push(goTo(24), list, false);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PTrommelScript node1 = (PTrommelScript) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AProfileDataTrommelScript */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PTrommelScript ptrommelscriptNode1;
        {
            // Block
        PLoadDataStatement ploaddatastatementNode2;
        PProfileDataStatement pprofiledatastatementNode3;
        ploaddatastatementNode2 = (PLoadDataStatement)nodeArrayList1.get(0);
        pprofiledatastatementNode3 = (PProfileDataStatement)nodeArrayList2.get(0);

        ptrommelscriptNode1 = new AProfileDataTrommelScript(ploaddatastatementNode2, pprofiledatastatementNode3);
        }
	nodeList.add(ptrommelscriptNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AReportDataTrommelScript */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PTrommelScript ptrommelscriptNode1;
        {
            // Block
        PLoadDataStatement ploaddatastatementNode2;
        PReportDataStatement preportdatastatementNode3;
        ploaddatastatementNode2 = (PLoadDataStatement)nodeArrayList1.get(0);
        preportdatastatementNode3 = (PReportDataStatement)nodeArrayList2.get(0);

        ptrommelscriptNode1 = new AReportDataTrommelScript(ploaddatastatementNode2, preportdatastatementNode3);
        }
	nodeList.add(ptrommelscriptNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce ASampleDataTrommelScript */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PTrommelScript ptrommelscriptNode1;
        {
            // Block
        PSampleDataStatement psampledatastatementNode2;
        psampledatastatementNode2 = (PSampleDataStatement)nodeArrayList1.get(0);

        ptrommelscriptNode1 = new ASampleDataTrommelScript(psampledatastatementNode2);
        }
	nodeList.add(ptrommelscriptNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce ALoadDataStatement */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList6 = pop();
         ArrayList nodeArrayList5 = pop();
         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PLoadDataStatement ploaddatastatementNode1;
        {
            // Block
        TLoad tloadNode2;
        TData tdataNode3;
        PLoadedFile ploadedfileNode4;
        TAs tasNode5;
        PLoadedFields ploadedfieldsNode6;
        PFieldsTerminatedBy pfieldsterminatedbyNode7;
        tloadNode2 = (TLoad)nodeArrayList1.get(0);
        tdataNode3 = (TData)nodeArrayList2.get(0);
        ploadedfileNode4 = (PLoadedFile)nodeArrayList3.get(0);
        tasNode5 = (TAs)nodeArrayList4.get(0);
        ploadedfieldsNode6 = (PLoadedFields)nodeArrayList5.get(0);
        pfieldsterminatedbyNode7 = (PFieldsTerminatedBy)nodeArrayList6.get(0);

        ploaddatastatementNode1 = new ALoadDataStatement(tloadNode2, tdataNode3, ploadedfileNode4, tasNode5, ploadedfieldsNode6, pfieldsterminatedbyNode7);
        }
	nodeList.add(ploaddatastatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce ALoadedFile */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PLoadedFile ploadedfileNode1;
        {
            // Block
        TQuotedString tquotedstringNode2;
        tquotedstringNode2 = (TQuotedString)nodeArrayList1.get(0);

        ploadedfileNode1 = new ALoadedFile(tquotedstringNode2);
        }
	nodeList.add(ploadedfileNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce ALoadedFields */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PLoadedFields ploadedfieldsNode1;
        {
            // Block
        TLeftParen tleftparenNode2;
        PFieldList pfieldlistNode3;
        TRightParen trightparenNode4;
        tleftparenNode2 = (TLeftParen)nodeArrayList1.get(0);
        pfieldlistNode3 = (PFieldList)nodeArrayList2.get(0);
        trightparenNode4 = (TRightParen)nodeArrayList3.get(0);

        ploadedfieldsNode1 = new ALoadedFields(tleftparenNode2, pfieldlistNode3, trightparenNode4);
        }
	nodeList.add(ploadedfieldsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce ASingleFieldList */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFieldList pfieldlistNode1;
        {
            // Block
        PField pfieldNode2;
        pfieldNode2 = (PField)nodeArrayList1.get(0);

        pfieldlistNode1 = new ASingleFieldList(pfieldNode2);
        }
	nodeList.add(pfieldlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AListFieldList */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PFieldList pfieldlistNode1;
        {
            // Block
        PFieldList pfieldlistNode2;
        TComma tcommaNode3;
        PField pfieldNode4;
        pfieldlistNode2 = (PFieldList)nodeArrayList1.get(0);
        tcommaNode3 = (TComma)nodeArrayList2.get(0);
        pfieldNode4 = (PField)nodeArrayList3.get(0);

        pfieldlistNode1 = new AListFieldList(pfieldlistNode2, tcommaNode3, pfieldNode4);
        }
	nodeList.add(pfieldlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce AField */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PField pfieldNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        TColon tcolonNode3;
        TFieldType tfieldtypeNode4;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        tcolonNode3 = (TColon)nodeArrayList2.get(0);
        tfieldtypeNode4 = (TFieldType)nodeArrayList3.get(0);

        pfieldNode1 = new AField(tidentifierNode2, tcolonNode3, tfieldtypeNode4);
        }
	nodeList.add(pfieldNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce ADefaultFieldsTerminatedBy */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFieldsTerminatedBy pfieldsterminatedbyNode1;
        {
            // Block
        TSemicolon tsemicolonNode2;
        tsemicolonNode2 = (TSemicolon)nodeArrayList1.get(0);

        pfieldsterminatedbyNode1 = new ADefaultFieldsTerminatedBy(tsemicolonNode2);
        }
	nodeList.add(pfieldsterminatedbyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce ACustomFieldsTerminatedBy */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList5 = pop();
         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PFieldsTerminatedBy pfieldsterminatedbyNode1;
        {
            // Block
        TFields tfieldsNode2;
        TTerminated tterminatedNode3;
        TBy tbyNode4;
        PFieldTerminator pfieldterminatorNode5;
        TSemicolon tsemicolonNode6;
        tfieldsNode2 = (TFields)nodeArrayList1.get(0);
        tterminatedNode3 = (TTerminated)nodeArrayList2.get(0);
        tbyNode4 = (TBy)nodeArrayList3.get(0);
        pfieldterminatorNode5 = (PFieldTerminator)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        pfieldsterminatedbyNode1 = new ACustomFieldsTerminatedBy(tfieldsNode2, tterminatedNode3, tbyNode4, pfieldterminatorNode5, tsemicolonNode6);
        }
	nodeList.add(pfieldsterminatedbyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce AFieldTerminator */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFieldTerminator pfieldterminatorNode1;
        {
            // Block
        TQuotedString tquotedstringNode2;
        tquotedstringNode2 = (TQuotedString)nodeArrayList1.get(0);

        pfieldterminatorNode1 = new AFieldTerminator(tquotedstringNode2);
        }
	nodeList.add(pfieldterminatorNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce AProfileDataStatement */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList6 = pop();
         ArrayList nodeArrayList5 = pop();
         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PProfileDataStatement pprofiledatastatementNode1;
        {
            // Block
        TProfile tprofileNode2;
        PProfiledFields pprofiledfieldsNode3;
        TWith twithNode4;
        PProfilers pprofilersNode5;
        PStorage pstorageNode6;
        TSemicolon tsemicolonNode7;
        tprofileNode2 = (TProfile)nodeArrayList1.get(0);
        pprofiledfieldsNode3 = (PProfiledFields)nodeArrayList2.get(0);
        twithNode4 = (TWith)nodeArrayList3.get(0);
        pprofilersNode5 = (PProfilers)nodeArrayList4.get(0);
        pstorageNode6 = (PStorage)nodeArrayList5.get(0);
        tsemicolonNode7 = (TSemicolon)nodeArrayList6.get(0);

        pprofiledatastatementNode1 = new AProfileDataStatement(tprofileNode2, pprofiledfieldsNode3, twithNode4, pprofilersNode5, pstorageNode6, tsemicolonNode7);
        }
	nodeList.add(pprofiledatastatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce ASingleProfiledFields */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PProfiledFields pprofiledfieldsNode1;
        {
            // Block
        PProfiledField pprofiledfieldNode2;
        pprofiledfieldNode2 = (PProfiledField)nodeArrayList1.get(0);

        pprofiledfieldsNode1 = new ASingleProfiledFields(pprofiledfieldNode2);
        }
	nodeList.add(pprofiledfieldsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce AListProfiledFields */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PProfiledFields pprofiledfieldsNode1;
        {
            // Block
        PProfiledFields pprofiledfieldsNode2;
        TComma tcommaNode3;
        PProfiledField pprofiledfieldNode4;
        pprofiledfieldsNode2 = (PProfiledFields)nodeArrayList1.get(0);
        tcommaNode3 = (TComma)nodeArrayList2.get(0);
        pprofiledfieldNode4 = (PProfiledField)nodeArrayList3.get(0);

        pprofiledfieldsNode1 = new AListProfiledFields(pprofiledfieldsNode2, tcommaNode3, pprofiledfieldNode4);
        }
	nodeList.add(pprofiledfieldsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce AProfiledField */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PProfiledField pprofiledfieldNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        pprofiledfieldNode1 = new AProfiledField(tidentifierNode2);
        }
	nodeList.add(pprofiledfieldNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AListProfilers */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PProfilers pprofilersNode1;
        {
            // Block
        PFunctionList pfunctionlistNode2;
        pfunctionlistNode2 = (PFunctionList)nodeArrayList1.get(0);

        pprofilersNode1 = new AListProfilers(pfunctionlistNode2);
        }
	nodeList.add(pprofilersNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AAllBuiltinProfilers */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PProfilers pprofilersNode1;
        {
            // Block
        TAll tallNode2;
        TBuiltin tbuiltinNode3;
        tallNode2 = (TAll)nodeArrayList1.get(0);
        tbuiltinNode3 = (TBuiltin)nodeArrayList2.get(0);

        pprofilersNode1 = new AAllBuiltinProfilers(tallNode2, tbuiltinNode3);
        }
	nodeList.add(pprofilersNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce ASingleFunctionList */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunctionList pfunctionlistNode1;
        {
            // Block
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pfunctionlistNode1 = new ASingleFunctionList(pfunctionNode2);
        }
	nodeList.add(pfunctionlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce AListFunctionList */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PFunctionList pfunctionlistNode1;
        {
            // Block
        PFunctionList pfunctionlistNode2;
        TComma tcommaNode3;
        PFunction pfunctionNode4;
        pfunctionlistNode2 = (PFunctionList)nodeArrayList1.get(0);
        tcommaNode3 = (TComma)nodeArrayList2.get(0);
        pfunctionNode4 = (PFunction)nodeArrayList3.get(0);

        pfunctionlistNode1 = new AListFunctionList(pfunctionlistNode2, tcommaNode3, pfunctionNode4);
        }
	nodeList.add(pfunctionlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce AMaxFunction */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunction pfunctionNode1;
        {
            // Block
        TMax tmaxNode2;
        tmaxNode2 = (TMax)nodeArrayList1.get(0);

        pfunctionNode1 = new AMaxFunction(tmaxNode2);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AMinFunction */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunction pfunctionNode1;
        {
            // Block
        TMin tminNode2;
        tminNode2 = (TMin)nodeArrayList1.get(0);

        pfunctionNode1 = new AMinFunction(tminNode2);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce ADistinctFunction */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunction pfunctionNode1;
        {
            // Block
        TDistinct tdistinctNode2;
        tdistinctNode2 = (TDistinct)nodeArrayList1.get(0);

        pfunctionNode1 = new ADistinctFunction(tdistinctNode2);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce AEmptyFunction */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunction pfunctionNode1;
        {
            // Block
        TEmpty temptyNode2;
        temptyNode2 = (TEmpty)nodeArrayList1.get(0);

        pfunctionNode1 = new AEmptyFunction(temptyNode2);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce AReqFunction */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunction pfunctionNode1;
        {
            // Block
        TReq treqNode2;
        treqNode2 = (TReq)nodeArrayList1.get(0);

        pfunctionNode1 = new AReqFunction(treqNode2);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AVarFunction */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunction pfunctionNode1;
        {
            // Block
        TVar tvarNode2;
        tvarNode2 = (TVar)nodeArrayList1.get(0);

        pfunctionNode1 = new AVarFunction(tvarNode2);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce ALinFunction */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunction pfunctionNode1;
        {
            // Block
        PLinearity plinearityNode2;
        plinearityNode2 = (PLinearity)nodeArrayList1.get(0);

        pfunctionNode1 = new ALinFunction(plinearityNode2);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce AConfFunction */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PFunction pfunctionNode1;
        {
            // Block
        PConfidence pconfidenceNode2;
        pconfidenceNode2 = (PConfidence)nodeArrayList1.get(0);

        pfunctionNode1 = new AConfFunction(pconfidenceNode2);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce ADefaultLinearity */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PLinearity plinearityNode1;
        {
            // Block
        TLin tlinNode2;
        tlinNode2 = (TLin)nodeArrayList1.get(0);

        plinearityNode1 = new ADefaultLinearity(tlinNode2);
        }
	nodeList.add(plinearityNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce ADefaultParenLinearity */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PLinearity plinearityNode1;
        {
            // Block
        TLin tlinNode2;
        TLeftParen tleftparenNode3;
        TRightParen trightparenNode4;
        tlinNode2 = (TLin)nodeArrayList1.get(0);
        tleftparenNode3 = (TLeftParen)nodeArrayList2.get(0);
        trightparenNode4 = (TRightParen)nodeArrayList3.get(0);

        plinearityNode1 = new ADefaultParenLinearity(tlinNode2, tleftparenNode3, trightparenNode4);
        }
	nodeList.add(plinearityNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce AParmLinearity */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PLinearity plinearityNode1;
        {
            // Block
        TLin tlinNode2;
        TLeftParen tleftparenNode3;
        TInteger tintegerNode4;
        TRightParen trightparenNode5;
        tlinNode2 = (TLin)nodeArrayList1.get(0);
        tleftparenNode3 = (TLeftParen)nodeArrayList2.get(0);
        tintegerNode4 = (TInteger)nodeArrayList3.get(0);
        trightparenNode5 = (TRightParen)nodeArrayList4.get(0);

        plinearityNode1 = new AParmLinearity(tlinNode2, tleftparenNode3, tintegerNode4, trightparenNode5);
        }
	nodeList.add(plinearityNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce ADefaultConfidence */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PConfidence pconfidenceNode1;
        {
            // Block
        TConf tconfNode2;
        tconfNode2 = (TConf)nodeArrayList1.get(0);

        pconfidenceNode1 = new ADefaultConfidence(tconfNode2);
        }
	nodeList.add(pconfidenceNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce ADefaultParenConfidence */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PConfidence pconfidenceNode1;
        {
            // Block
        TConf tconfNode2;
        TLeftParen tleftparenNode3;
        TRightParen trightparenNode4;
        tconfNode2 = (TConf)nodeArrayList1.get(0);
        tleftparenNode3 = (TLeftParen)nodeArrayList2.get(0);
        trightparenNode4 = (TRightParen)nodeArrayList3.get(0);

        pconfidenceNode1 = new ADefaultParenConfidence(tconfNode2, tleftparenNode3, trightparenNode4);
        }
	nodeList.add(pconfidenceNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce AParmConfidence */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PConfidence pconfidenceNode1;
        {
            // Block
        TConf tconfNode2;
        TLeftParen tleftparenNode3;
        TInteger tintegerNode4;
        TRightParen trightparenNode5;
        tconfNode2 = (TConf)nodeArrayList1.get(0);
        tleftparenNode3 = (TLeftParen)nodeArrayList2.get(0);
        tintegerNode4 = (TInteger)nodeArrayList3.get(0);
        trightparenNode5 = (TRightParen)nodeArrayList4.get(0);

        pconfidenceNode1 = new AParmConfidence(tconfNode2, tleftparenNode3, tintegerNode4, trightparenNode5);
        }
	nodeList.add(pconfidenceNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new34() /* reduce AReportDataStatement */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList6 = pop();
         ArrayList nodeArrayList5 = pop();
         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PReportDataStatement preportdatastatementNode1;
        {
            // Block
        TReport treportNode2;
        TData tdataNode3;
        TFor tforNode4;
        PReportedFields preportedfieldsNode5;
        PStorage pstorageNode6;
        TSemicolon tsemicolonNode7;
        treportNode2 = (TReport)nodeArrayList1.get(0);
        tdataNode3 = (TData)nodeArrayList2.get(0);
        tforNode4 = (TFor)nodeArrayList3.get(0);
        preportedfieldsNode5 = (PReportedFields)nodeArrayList4.get(0);
        pstorageNode6 = (PStorage)nodeArrayList5.get(0);
        tsemicolonNode7 = (TSemicolon)nodeArrayList6.get(0);

        preportdatastatementNode1 = new AReportDataStatement(treportNode2, tdataNode3, tforNode4, preportedfieldsNode5, pstorageNode6, tsemicolonNode7);
        }
	nodeList.add(preportdatastatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new35() /* reduce ASingleReportedFields */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PReportedFields preportedfieldsNode1;
        {
            // Block
        PReportedField preportedfieldNode2;
        preportedfieldNode2 = (PReportedField)nodeArrayList1.get(0);

        preportedfieldsNode1 = new ASingleReportedFields(preportedfieldNode2);
        }
	nodeList.add(preportedfieldsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new36() /* reduce AListReportedFields */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PReportedFields preportedfieldsNode1;
        {
            // Block
        PReportedFields preportedfieldsNode2;
        TComma tcommaNode3;
        PReportedField preportedfieldNode4;
        preportedfieldsNode2 = (PReportedFields)nodeArrayList1.get(0);
        tcommaNode3 = (TComma)nodeArrayList2.get(0);
        preportedfieldNode4 = (PReportedField)nodeArrayList3.get(0);

        preportedfieldsNode1 = new AListReportedFields(preportedfieldsNode2, tcommaNode3, preportedfieldNode4);
        }
	nodeList.add(preportedfieldsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new37() /* reduce AReportedField */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PReportedField preportedfieldNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        preportedfieldNode1 = new AReportedField(tidentifierNode2);
        }
	nodeList.add(preportedfieldNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new38() /* reduce ASampleDataStatement */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList7 = pop();
         ArrayList nodeArrayList6 = pop();
         ArrayList nodeArrayList5 = pop();
         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PSampleDataStatement psampledatastatementNode1;
        {
            // Block
        TSample tsampleNode2;
        TData tdataNode3;
        PSampledFile psampledfileNode4;
        TAt tatNode5;
        PSampleRate psamplerateNode6;
        PStorage pstorageNode7;
        TSemicolon tsemicolonNode8;
        tsampleNode2 = (TSample)nodeArrayList1.get(0);
        tdataNode3 = (TData)nodeArrayList2.get(0);
        psampledfileNode4 = (PSampledFile)nodeArrayList3.get(0);
        tatNode5 = (TAt)nodeArrayList4.get(0);
        psamplerateNode6 = (PSampleRate)nodeArrayList5.get(0);
        pstorageNode7 = (PStorage)nodeArrayList6.get(0);
        tsemicolonNode8 = (TSemicolon)nodeArrayList7.get(0);

        psampledatastatementNode1 = new ASampleDataStatement(tsampleNode2, tdataNode3, psampledfileNode4, tatNode5, psamplerateNode6, pstorageNode7, tsemicolonNode8);
        }
	nodeList.add(psampledatastatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new39() /* reduce ASampledFile */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PSampledFile psampledfileNode1;
        {
            // Block
        TQuotedString tquotedstringNode2;
        tquotedstringNode2 = (TQuotedString)nodeArrayList1.get(0);

        psampledfileNode1 = new ASampledFile(tquotedstringNode2);
        }
	nodeList.add(psampledfileNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new40() /* reduce ASampleRate */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PSampleRate psamplerateNode1;
        {
            // Block
        TInteger tintegerNode2;
        TPercent tpercentNode3;
        tintegerNode2 = (TInteger)nodeArrayList1.get(0);
        tpercentNode3 = (TPercent)nodeArrayList2.get(0);

        psamplerateNode1 = new ASampleRate(tintegerNode2, tpercentNode3);
        }
	nodeList.add(psamplerateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new41() /* reduce AStoreStorage */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PStorage pstorageNode1;
        {
            // Block
        TStore tstoreNode2;
        TInto tintoNode3;
        PHdfsFilePath phdfsfilepathNode4;
        tstoreNode2 = (TStore)nodeArrayList1.get(0);
        tintoNode3 = (TInto)nodeArrayList2.get(0);
        phdfsfilepathNode4 = (PHdfsFilePath)nodeArrayList3.get(0);

        pstorageNode1 = new AStoreStorage(tstoreNode2, tintoNode3, phdfsfilepathNode4);
        }
	nodeList.add(pstorageNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new42() /* reduce AExportStorage */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PStorage pstorageNode1;
        {
            // Block
        TExport texportNode2;
        TTo ttoNode3;
        PLocalFilePath plocalfilepathNode4;
        texportNode2 = (TExport)nodeArrayList1.get(0);
        ttoNode3 = (TTo)nodeArrayList2.get(0);
        plocalfilepathNode4 = (PLocalFilePath)nodeArrayList3.get(0);

        pstorageNode1 = new AExportStorage(texportNode2, ttoNode3, plocalfilepathNode4);
        }
	nodeList.add(pstorageNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new43() /* reduce AStoreExportStorage */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList6 = pop();
         ArrayList nodeArrayList5 = pop();
         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PStorage pstorageNode1;
        {
            // Block
        TStore tstoreNode2;
        TInto tintoNode3;
        PHdfsFilePath phdfsfilepathNode4;
        TExport texportNode5;
        TTo ttoNode6;
        PLocalFilePath plocalfilepathNode7;
        tstoreNode2 = (TStore)nodeArrayList1.get(0);
        tintoNode3 = (TInto)nodeArrayList2.get(0);
        phdfsfilepathNode4 = (PHdfsFilePath)nodeArrayList3.get(0);
        texportNode5 = (TExport)nodeArrayList4.get(0);
        ttoNode6 = (TTo)nodeArrayList5.get(0);
        plocalfilepathNode7 = (PLocalFilePath)nodeArrayList6.get(0);

        pstorageNode1 = new AStoreExportStorage(tstoreNode2, tintoNode3, phdfsfilepathNode4, texportNode5, ttoNode6, plocalfilepathNode7);
        }
	nodeList.add(pstorageNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new44() /* reduce AExportStoreStorage */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList6 = pop();
         ArrayList nodeArrayList5 = pop();
         ArrayList nodeArrayList4 = pop();
         ArrayList nodeArrayList3 = pop();
         ArrayList nodeArrayList2 = pop();
         ArrayList nodeArrayList1 = pop();
        PStorage pstorageNode1;
        {
            // Block
        TExport texportNode2;
        TTo ttoNode3;
        PLocalFilePath plocalfilepathNode4;
        TStore tstoreNode5;
        TInto tintoNode6;
        PHdfsFilePath phdfsfilepathNode7;
        texportNode2 = (TExport)nodeArrayList1.get(0);
        ttoNode3 = (TTo)nodeArrayList2.get(0);
        plocalfilepathNode4 = (PLocalFilePath)nodeArrayList3.get(0);
        tstoreNode5 = (TStore)nodeArrayList4.get(0);
        tintoNode6 = (TInto)nodeArrayList5.get(0);
        phdfsfilepathNode7 = (PHdfsFilePath)nodeArrayList6.get(0);

        pstorageNode1 = new AExportStoreStorage(texportNode2, ttoNode3, plocalfilepathNode4, tstoreNode5, tintoNode6, phdfsfilepathNode7);
        }
	nodeList.add(pstorageNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new45() /* reduce AHdfsFilePath */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PHdfsFilePath phdfsfilepathNode1;
        {
            // Block
        TQuotedString tquotedstringNode2;
        tquotedstringNode2 = (TQuotedString)nodeArrayList1.get(0);

        phdfsfilepathNode1 = new AHdfsFilePath(tquotedstringNode2);
        }
	nodeList.add(phdfsfilepathNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new46() /* reduce ALocalFilePath */
    {
         ArrayList nodeList = new ArrayList();

         ArrayList nodeArrayList1 = pop();
        PLocalFilePath plocalfilepathNode1;
        {
            // Block
        TQuotedString tquotedstringNode2;
        tquotedstringNode2 = (TQuotedString)nodeArrayList1.get(0);

        plocalfilepathNode1 = new ALocalFilePath(tquotedstringNode2);
        }
	nodeList.add(plocalfilepathNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, {20, SHIFT, 2}, },
			{{-1, ERROR, 1}, {23, SHIFT, 6}, },
			{{-1, ERROR, 2}, {23, SHIFT, 7}, },
			{{-1, ERROR, 3}, {36, ACCEPT, -1}, },
			{{-1, ERROR, 4}, {6, SHIFT, 8}, {18, SHIFT, 9}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 6}, {33, SHIFT, 12}, },
			{{-1, ERROR, 7}, {33, SHIFT, 14}, },
			{{-1, ERROR, 8}, {34, SHIFT, 16}, },
			{{-1, ERROR, 9}, {23, SHIFT, 19}, },
			{{-1, REDUCE, 0}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 13}, {32, SHIFT, 20}, },
			{{-1, REDUCE, 39}, },
			{{-1, ERROR, 15}, {21, SHIFT, 21}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 17}, {7, SHIFT, 22}, {31, SHIFT, 23}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 19}, {19, SHIFT, 24}, },
			{{-1, ERROR, 20}, {29, SHIFT, 25}, },
			{{-1, ERROR, 21}, {35, SHIFT, 27}, },
			{{-1, ERROR, 22}, {8, SHIFT, 29}, {10, SHIFT, 30}, {11, SHIFT, 31}, {12, SHIFT, 32}, {13, SHIFT, 33}, {14, SHIFT, 34}, {15, SHIFT, 35}, {16, SHIFT, 36}, {17, SHIFT, 37}, },
			{{-1, ERROR, 23}, {34, SHIFT, 16}, },
			{{-1, ERROR, 24}, {34, SHIFT, 44}, },
			{{-1, ERROR, 25}, {34, SHIFT, 47}, },
			{{-1, ERROR, 26}, {3, SHIFT, 50}, {28, SHIFT, 51}, },
			{{-1, ERROR, 27}, {22, SHIFT, 53}, },
			{{-1, ERROR, 28}, {24, SHIFT, 54}, {26, SHIFT, 55}, },
			{{-1, ERROR, 29}, {9, SHIFT, 57}, },
			{{-1, REDUCE, 20}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 31}, {29, SHIFT, 58}, },
			{{-1, REDUCE, 28}, {29, SHIFT, 59}, },
			{{-1, ERROR, 38}, {24, SHIFT, 54}, {26, SHIFT, 55}, },
			{{-1, REDUCE, 16}, {31, SHIFT, 61}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 37}, },
			{{-1, ERROR, 45}, {24, SHIFT, 54}, {26, SHIFT, 55}, {31, SHIFT, 62}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 47}, {1, SHIFT, 64}, },
			{{-1, ERROR, 48}, {30, SHIFT, 65}, {31, SHIFT, 66}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 50}, {4, SHIFT, 67}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 54}, {25, SHIFT, 68}, },
			{{-1, ERROR, 55}, {27, SHIFT, 69}, },
			{{-1, ERROR, 56}, {28, SHIFT, 70}, },
			{{-1, REDUCE, 17}, },
			{{-1, ERROR, 58}, {30, SHIFT, 71}, {35, SHIFT, 72}, },
			{{-1, ERROR, 59}, {30, SHIFT, 73}, {35, SHIFT, 74}, },
			{{-1, ERROR, 60}, {28, SHIFT, 75}, },
			{{-1, ERROR, 61}, {10, SHIFT, 30}, {11, SHIFT, 31}, {12, SHIFT, 32}, {13, SHIFT, 33}, {14, SHIFT, 34}, {15, SHIFT, 35}, {16, SHIFT, 36}, {17, SHIFT, 37}, },
			{{-1, ERROR, 62}, {34, SHIFT, 44}, },
			{{-1, ERROR, 63}, {28, SHIFT, 78}, },
			{{-1, ERROR, 64}, {2, SHIFT, 79}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 66}, {34, SHIFT, 47}, },
			{{-1, ERROR, 67}, {5, SHIFT, 81}, },
			{{-1, ERROR, 68}, {33, SHIFT, 82}, },
			{{-1, ERROR, 69}, {33, SHIFT, 84}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 72}, {30, SHIFT, 86}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 74}, {30, SHIFT, 87}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 81}, {33, SHIFT, 88}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 41}, {26, SHIFT, 90}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 42}, {24, SHIFT, 91}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 89}, {28, SHIFT, 92}, },
			{{-1, ERROR, 90}, {27, SHIFT, 93}, },
			{{-1, ERROR, 91}, {25, SHIFT, 94}, },
			{{-1, REDUCE, 10}, },
			{{-1, ERROR, 93}, {33, SHIFT, 84}, },
			{{-1, ERROR, 94}, {33, SHIFT, 82}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 44}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 3}, },
			{{-1, 4}, },
			{{-1, 13}, },
			{{-1, 26}, },
			{{-1, 48}, },
			{{-1, 49}, {66, 80}, },
			{{-1, 52}, },
			{{-1, 89}, },
			{{-1, 10}, },
			{{-1, 17}, },
			{{-1, 18}, {23, 43}, },
			{{-1, 38}, },
			{{-1, 39}, },
			{{-1, 40}, {61, 76}, },
			{{-1, 41}, },
			{{-1, 42}, },
			{{-1, 11}, },
			{{-1, 45}, },
			{{-1, 46}, {62, 77}, },
			{{-1, 5}, },
			{{-1, 15}, },
			{{-1, 28}, },
			{{-1, 56}, {38, 60}, {45, 63}, },
			{{-1, 83}, {94, 96}, },
			{{-1, 85}, {93, 95}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: load, sample",
			"expecting: data",
			"expecting: EOF",
			"expecting: profile, report",
			"expecting: quoted string",
			"expecting: identifier",
			"expecting: as",
			"expecting: at",
			"expecting: with, ','",
			"expecting: for",
			"expecting: '('",
			"expecting: integer",
			"expecting: all, max, min, distinct, empty, req, var, conf, lin",
			"expecting: fields, ';'",
			"expecting: '%'",
			"expecting: store, export",
			"expecting: builtin",
			"expecting: store, export, ','",
			"expecting: store, export, '(', ','",
			"expecting: ':'",
			"expecting: ')', ','",
			"expecting: terminated",
			"expecting: into",
			"expecting: to",
			"expecting: ';'",
			"expecting: ')', integer",
			"expecting: max, min, distinct, empty, req, var, conf, lin",
			"expecting: field type",
			"expecting: by",
			"expecting: ')'",
			"expecting: export, ';'",
			"expecting: store, ';'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 2, 3, 2, 4, 4, 5, 1, 2, 2, 6, 6, 7, 7, 8, 8, 8, 9, 10, 11, 12, 5, 5, 5, 13, 14, 15, 16, 17, 17, 17, 17, 17, 17, 18, 18, 15, 17, 17, 17, 17, 8, 17, 17, 17, 19, 20, 20, 21, 3, 3, 15, 22, 23, 24, 15, 25, 25, 24, 26, 5, 24, 27, 13, 5, 28, 4, 4, 2, 17, 29, 17, 29, 2, 17, 17, 2, 20, 20, 4, 30, 30, 31, 31, 17, 17, 24, 24, 23, 22, 3, 4, 4, 24, 24, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
