/** This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.parser;

import java.util.ArrayList;

@SuppressWarnings("rawtypes")
final class State
{
    int state;
    ArrayList nodes;

	State( int state,  ArrayList nodes)
    {
        this.state = state;
        this.nodes = nodes;
    }
}
