/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.trommel.trommel.scripting.lexer;

import java.io.*;
import org.trommel.trommel.scripting.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLoad(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFieldType(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFields(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTerminated(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBy(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProfile(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWith(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAll(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBuiltin(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMax(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMin(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDistinct(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEmpty(text, line, pos); }
    Token new14(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReq(text, line, pos); }
    Token new15(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(text, line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConf(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLin(text, line, pos); }
    Token new18(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReport(text, line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TData(text, line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStore(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInto(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TExport(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTo(text, line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftParen(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightParen(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new29(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAs(text, line, pos); }
    Token new30(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQuotedString(text, line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteger(text, line, pos); }
    Token new33(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlockComment(text, line, pos); }
    Token new34(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSingleLineComment(text, line, pos); }
    Token new35(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhiteSpace(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {12, 12, 3}, {13, 13, 4}, {32, 32, 5}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {44, 44, 9}, {47, 47, 10}, {48, 57, 11}, {58, 58, 12}, {59, 59, 13}, {65, 65, 14}, {66, 66, 15}, {67, 67, 16}, {68, 68, 17}, {69, 69, 18}, {70, 70, 19}, {71, 72, 20}, {73, 73, 21}, {74, 75, 20}, {76, 76, 22}, {77, 77, 23}, {78, 78, 24}, {79, 79, 20}, {80, 80, 25}, {81, 81, 20}, {82, 82, 26}, {83, 83, 27}, {84, 84, 28}, {85, 85, 20}, {86, 86, 29}, {87, 87, 30}, {88, 90, 20}, {97, 97, 31}, {98, 98, 32}, {99, 99, 33}, {100, 100, 34}, {101, 101, 35}, {102, 102, 36}, {103, 104, 20}, {105, 105, 37}, {106, 107, 20}, {108, 108, 38}, {109, 109, 39}, {110, 110, 40}, {111, 111, 20}, {112, 112, 41}, {113, 113, 20}, {114, 114, 42}, {115, 115, 43}, {116, 116, 44}, {117, 117, 20}, {118, 118, 45}, {119, 119, 46}, {120, 122, 20}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 47}, {12, 32, -2}, },
            {{9, 32, -2}, },
            {{32, 38, 48}, {40, 126, 48}, },
            {},
            {},
            {},
            {{42, 42, 49}, {47, 47, 50}, },
            {{48, 57, 11}, },
            {},
            {},
            {{48, 57, 51}, {65, 75, 52}, {76, 76, 53}, {77, 82, 52}, {83, 83, 54}, {84, 90, 52}, {95, 95, 55}, {97, 122, 52}, },
            {{48, 57, 51}, {65, 84, 52}, {85, 85, 56}, {86, 88, 52}, {89, 89, 57}, {90, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 65, 58}, {66, 78, 52}, {79, 79, 59}, {80, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 65, 60}, {66, 72, 52}, {73, 73, 61}, {74, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 76, 52}, {77, 77, 62}, {78, 87, 52}, {88, 88, 63}, {89, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 72, 52}, {73, 73, 64}, {74, 78, 52}, {79, 79, 65}, {80, 122, -18}, },
            {{48, 57, 51}, {65, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 77, 52}, {78, 78, 66}, {79, 90, 52}, {95, 122, -16}, },
            {{48, 72, -21}, {73, 73, 67}, {74, 78, 52}, {79, 79, 68}, {80, 122, -18}, },
            {{48, 57, 51}, {65, 65, 69}, {66, 72, 52}, {73, 73, 70}, {74, 122, -19}, },
            {{48, 84, -17}, {85, 85, 71}, {86, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 81, 52}, {82, 82, 72}, {83, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 68, 52}, {69, 69, 73}, {70, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 83, 52}, {84, 84, 74}, {85, 90, 52}, {95, 122, -16}, },
            {{48, 68, -28}, {69, 69, 75}, {70, 78, 52}, {79, 79, 76}, {80, 122, -18}, },
            {{48, 57, 51}, {65, 65, 77}, {66, 90, 52}, {95, 122, -16}, },
            {{48, 72, -21}, {73, 73, 78}, {74, 122, -19}, },
            {{48, 95, -22}, {97, 107, 52}, {108, 108, 79}, {109, 114, 52}, {115, 115, 80}, {116, 122, 52}, },
            {{48, 95, -22}, {97, 116, 52}, {117, 117, 81}, {118, 120, 52}, {121, 121, 82}, {122, 122, 52}, },
            {{48, 95, -22}, {97, 97, 83}, {98, 110, 52}, {111, 111, 84}, {112, 122, 52}, },
            {{48, 95, -22}, {97, 97, 85}, {98, 104, 52}, {105, 105, 86}, {106, 122, 52}, },
            {{48, 95, -22}, {97, 108, 52}, {109, 109, 87}, {110, 119, 52}, {120, 120, 88}, {121, 122, 52}, },
            {{48, 95, -22}, {97, 104, 52}, {105, 105, 89}, {106, 110, 52}, {111, 111, 90}, {112, 122, 52}, },
            {{48, 95, -22}, {97, 109, 52}, {110, 110, 91}, {111, 122, 52}, },
            {{48, 104, -38}, {105, 105, 92}, {106, 110, 52}, {111, 111, 93}, {112, 122, 52}, },
            {{48, 95, -22}, {97, 97, 94}, {98, 104, 52}, {105, 105, 95}, {106, 122, 52}, },
            {{48, 116, -34}, {117, 117, 96}, {118, 122, 52}, },
            {{48, 95, -22}, {97, 113, 52}, {114, 114, 97}, {115, 122, 52}, },
            {{48, 95, -22}, {97, 100, 52}, {101, 101, 98}, {102, 122, 52}, },
            {{48, 95, -22}, {97, 115, 52}, {116, 116, 99}, {117, 122, 52}, },
            {{48, 100, -44}, {101, 101, 100}, {102, 110, 52}, {111, 111, 101}, {112, 122, 52}, },
            {{48, 95, -22}, {97, 97, 102}, {98, 122, 52}, },
            {{48, 104, -38}, {105, 105, 103}, {106, 122, 52}, },
            {{9, 32, -2}, },
            {{32, 38, 48}, {39, 39, 104}, {40, 126, 48}, },
            {{9, 9, 105}, {10, 10, 106}, {13, 13, 107}, {32, 41, 108}, {42, 42, 109}, {43, 126, 108}, },
            {{10, 10, 110}, {13, 13, 111}, {32, 126, 112}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 75, -16}, {76, 76, 113}, {77, 90, 52}, {95, 122, -16}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 72, -21}, {73, 73, 114}, {74, 122, -19}, },
            {{48, 122, -22}, },
            {{48, 83, -29}, {84, 84, 115}, {85, 122, -29}, },
            {{48, 77, -23}, {78, 78, 116}, {79, 122, -23}, },
            {{48, 83, -29}, {84, 84, 117}, {85, 122, -29}, },
            {{48, 57, 51}, {65, 82, 52}, {83, 83, 118}, {84, 122, -16}, },
            {{48, 57, 51}, {65, 79, 52}, {80, 80, 119}, {81, 90, 52}, {95, 122, -16}, },
            {{48, 79, -64}, {80, 80, 120}, {81, 122, -64}, },
            {{48, 68, -28}, {69, 69, 121}, {70, 122, -28}, },
            {{48, 81, -27}, {82, 82, 122}, {83, 122, -27}, },
            {{48, 83, -29}, {84, 84, 123}, {85, 122, -29}, },
            {{48, 77, -23}, {78, 78, 124}, {79, 122, -23}, },
            {{48, 57, 51}, {65, 65, 125}, {66, 122, -31}, },
            {{48, 57, 51}, {65, 87, 52}, {88, 88, 126}, {89, 122, -20}, },
            {{48, 77, -23}, {78, 78, 127}, {79, 122, -23}, },
            {{48, 76, -20}, {77, 77, 128}, {78, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 78, 52}, {79, 79, 129}, {80, 122, -18}, },
            {{48, 79, -64}, {80, 80, 130}, {81, 81, 131}, {82, 90, 52}, {95, 122, -16}, },
            {{48, 78, -74}, {79, 79, 132}, {80, 122, -18}, },
            {{48, 81, -27}, {82, 82, 133}, {83, 122, -27}, },
            {{48, 122, -22}, },
            {{48, 81, -27}, {82, 82, 134}, {83, 122, -27}, },
            {{48, 83, -29}, {84, 84, 135}, {85, 122, -29}, },
            {{48, 107, -33}, {108, 108, 136}, {109, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 104, -38}, {105, 105, 137}, {106, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 115, -45}, {116, 116, 138}, {117, 122, 52}, },
            {{48, 109, -39}, {110, 110, 139}, {111, 122, 52}, },
            {{48, 115, -45}, {116, 116, 140}, {117, 122, 52}, },
            {{48, 95, -22}, {97, 114, 52}, {115, 115, 141}, {116, 122, 52}, },
            {{48, 95, -22}, {97, 111, 52}, {112, 112, 142}, {113, 122, 52}, },
            {{48, 111, -89}, {112, 112, 143}, {113, 122, 52}, },
            {{48, 100, -44}, {101, 101, 144}, {102, 122, 52}, },
            {{48, 113, -43}, {114, 114, 145}, {115, 122, 52}, },
            {{48, 115, -45}, {116, 116, 146}, {117, 122, 52}, },
            {{48, 109, -39}, {110, 110, 147}, {111, 122, 52}, },
            {{48, 95, -22}, {97, 97, 148}, {98, 122, 52}, },
            {{48, 95, -22}, {97, 119, 52}, {120, 120, 149}, {121, 122, 52}, },
            {{48, 109, -39}, {110, 110, 150}, {111, 122, 52}, },
            {{48, 108, -37}, {109, 109, 151}, {110, 122, 52}, },
            {{48, 95, -22}, {97, 110, 52}, {111, 111, 152}, {112, 122, 52}, },
            {{48, 111, -89}, {112, 112, 153}, {113, 113, 154}, {114, 122, 52}, },
            {{48, 110, -99}, {111, 111, 155}, {112, 122, 52}, },
            {{48, 113, -43}, {114, 114, 156}, {115, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 113, -43}, {114, 114, 157}, {115, 122, 52}, },
            {{48, 115, -45}, {116, 116, 158}, {117, 122, 52}, },
            {},
            {{9, 126, -51}, },
            {{9, 126, -51}, },
            {{9, 9, 105}, {10, 10, 159}, {13, 126, -51}, },
            {{9, 126, -51}, },
            {{9, 42, -51}, {43, 46, 108}, {47, 47, 160}, {48, 126, 108}, },
            {},
            {{10, 10, 161}, },
            {{10, 126, -52}, },
            {{48, 122, -22}, },
            {{48, 75, -16}, {76, 76, 162}, {77, 122, -55}, },
            {{48, 68, -28}, {69, 69, 163}, {70, 122, -28}, },
            {{48, 57, 51}, {65, 69, 52}, {70, 70, 164}, {71, 90, 52}, {95, 122, -16}, },
            {{48, 57, 51}, {65, 65, 165}, {66, 122, -31}, },
            {{48, 83, -29}, {84, 84, 166}, {85, 122, -29}, },
            {{48, 83, -29}, {84, 84, 167}, {85, 122, -29}, },
            {{48, 78, -74}, {79, 79, 168}, {80, 122, -18}, },
            {{48, 75, -16}, {76, 76, 169}, {77, 122, -55}, },
            {{48, 122, -22}, },
            {{48, 78, -74}, {79, 79, 170}, {80, 122, -18}, },
            {{48, 122, -22}, },
            {{48, 57, 51}, {65, 67, 52}, {68, 68, 171}, {69, 90, 52}, {95, 122, -16}, },
            {{40, 40, 172}, {48, 122, -22}, },
            {{40, 40, 173}, {48, 122, -22}, },
            {{48, 68, -28}, {69, 69, 174}, {70, 122, -28}, },
            {{48, 69, -118}, {70, 70, 175}, {71, 122, -118}, },
            {{48, 78, -74}, {79, 79, 176}, {80, 122, -18}, },
            {{40, 40, 177}, {48, 122, -22}, },
            {{48, 81, -27}, {82, 82, 178}, {83, 122, -27}, },
            {{48, 76, -20}, {77, 77, 179}, {78, 122, -73}, },
            {{40, 40, 180}, {48, 122, -22}, },
            {{48, 57, 51}, {65, 71, 52}, {72, 72, 181}, {73, 90, 52}, {95, 122, -16}, },
            {{48, 122, -22}, },
            {{48, 107, -33}, {108, 108, 182}, {109, 122, 52}, },
            {{48, 100, -44}, {101, 101, 183}, {102, 122, 52}, },
            {{48, 95, -22}, {97, 101, 52}, {102, 102, 184}, {103, 122, 52}, },
            {{48, 95, -22}, {97, 97, 185}, {98, 122, 52}, },
            {{48, 115, -45}, {116, 116, 186}, {117, 122, 52}, },
            {{48, 115, -45}, {116, 116, 187}, {117, 122, 52}, },
            {{48, 110, -99}, {111, 111, 188}, {112, 122, 52}, },
            {{48, 107, -33}, {108, 108, 189}, {109, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 110, -99}, {111, 111, 190}, {112, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 99, 52}, {100, 100, 191}, {101, 122, 52}, },
            {{40, 40, 192}, {48, 122, -22}, },
            {{40, 40, 193}, {48, 122, -22}, },
            {{48, 100, -44}, {101, 101, 194}, {102, 122, 52}, },
            {{48, 101, -141}, {102, 102, 195}, {103, 122, 52}, },
            {{48, 110, -99}, {111, 111, 196}, {112, 122, 52}, },
            {{40, 40, 197}, {48, 122, -22}, },
            {{48, 113, -43}, {114, 114, 198}, {115, 122, 52}, },
            {{48, 108, -37}, {109, 109, 199}, {110, 122, 52}, },
            {{40, 40, 200}, {48, 122, -22}, },
            {{48, 95, -22}, {97, 103, 52}, {104, 104, 201}, {105, 122, 52}, },
            {{9, 126, -51}, },
            {{9, 126, -51}, },
            {},
            {{48, 83, -29}, {84, 84, 202}, {85, 122, -29}, },
            {{48, 57, 51}, {65, 70, 52}, {71, 71, 203}, {72, 90, 52}, {95, 122, -16}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 72, -21}, {73, 73, 204}, {74, 122, -19}, },
            {{48, 57, 51}, {65, 88, 52}, {89, 89, 205}, {90, 122, -17}, },
            {{48, 81, -27}, {82, 82, 206}, {83, 122, -27}, },
            {{48, 67, -127}, {68, 68, 207}, {69, 122, -127}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{41, 41, 208}, },
            {{41, 41, 209}, },
            {{48, 81, -27}, {82, 82, 210}, {83, 122, -27}, },
            {{48, 72, -21}, {73, 73, 211}, {74, 122, -19}, },
            {{48, 81, -27}, {82, 82, 212}, {83, 122, -27}, },
            {{41, 41, 213}, },
            {{48, 68, -28}, {69, 69, 214}, {70, 122, -28}, },
            {{48, 72, -21}, {73, 73, 215}, {74, 122, -19}, },
            {{41, 41, 216}, },
            {{48, 122, -22}, },
            {{48, 115, -45}, {116, 116, 217}, {117, 122, 52}, },
            {{48, 95, -22}, {97, 102, 52}, {103, 103, 218}, {104, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 104, -38}, {105, 105, 219}, {106, 122, 52}, },
            {{48, 95, -22}, {97, 120, 52}, {121, 121, 220}, {122, 122, 52}, },
            {{48, 113, -43}, {114, 114, 221}, {115, 122, 52}, },
            {{48, 99, -150}, {100, 100, 222}, {101, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{41, 41, 223}, },
            {{41, 41, 224}, },
            {{48, 113, -43}, {114, 114, 225}, {115, 122, 52}, },
            {{48, 104, -38}, {105, 105, 226}, {106, 122, 52}, },
            {{48, 113, -43}, {114, 114, 227}, {115, 122, 52}, },
            {{41, 41, 228}, },
            {{48, 100, -44}, {101, 101, 229}, {102, 122, 52}, },
            {{48, 104, -38}, {105, 105, 230}, {106, 122, 52}, },
            {{41, 41, 231}, },
            {{48, 122, -22}, },
            {{48, 72, -21}, {73, 73, 232}, {74, 122, -19}, },
            {{48, 78, -74}, {79, 79, 233}, {80, 122, -18}, },
            {{48, 77, -23}, {78, 78, 234}, {79, 122, -23}, },
            {{40, 40, 235}, {48, 122, -22}, },
            {{48, 83, -29}, {84, 84, 236}, {85, 122, -29}, },
            {{48, 82, -63}, {83, 83, 237}, {84, 122, -16}, },
            {},
            {},
            {{48, 72, -21}, {73, 73, 238}, {74, 122, -19}, },
            {{48, 75, -16}, {76, 76, 239}, {77, 122, -55}, },
            {{48, 83, -29}, {84, 84, 240}, {85, 122, -29}, },
            {},
            {{48, 122, -22}, },
            {{48, 77, -23}, {78, 78, 241}, {79, 122, -23}, },
            {},
            {{48, 104, -38}, {105, 105, 242}, {106, 122, 52}, },
            {{48, 110, -99}, {111, 111, 243}, {112, 122, 52}, },
            {{48, 109, -39}, {110, 110, 244}, {111, 122, 52}, },
            {{40, 40, 245}, {48, 122, -22}, },
            {{48, 115, -45}, {116, 116, 246}, {117, 122, 52}, },
            {{48, 114, -88}, {115, 115, 247}, {116, 122, 52}, },
            {},
            {},
            {{48, 104, -38}, {105, 105, 248}, {106, 122, 52}, },
            {{48, 107, -33}, {108, 108, 249}, {109, 122, 52}, },
            {{48, 115, -45}, {116, 116, 250}, {117, 122, 52}, },
            {},
            {{48, 122, -22}, },
            {{48, 109, -39}, {110, 110, 251}, {111, 122, 52}, },
            {},
            {{48, 77, -23}, {78, 78, 252}, {79, 122, -23}, },
            {{48, 81, -27}, {82, 82, 253}, {83, 122, -27}, },
            {{48, 57, 51}, {65, 66, 52}, {67, 67, 254}, {68, 90, 52}, {95, 122, -16}, },
            {{41, 41, 255}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 66, -236}, {67, 67, 256}, {68, 122, -236}, },
            {{48, 68, -28}, {69, 69, 257}, {70, 122, -28}, },
            {{48, 122, -22}, },
            {{48, 57, 51}, {65, 65, 258}, {66, 122, -31}, },
            {{48, 109, -39}, {110, 110, 259}, {111, 122, 52}, },
            {{48, 113, -43}, {114, 114, 260}, {115, 122, 52}, },
            {{48, 95, -22}, {97, 98, 52}, {99, 99, 261}, {100, 122, 52}, },
            {{41, 41, 262}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 98, -246}, {99, 99, 263}, {100, 122, 52}, },
            {{48, 100, -44}, {101, 101, 264}, {102, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 97, 265}, {98, 122, 52}, },
            {{48, 122, -22}, },
            {{48, 72, -21}, {73, 73, 266}, {74, 122, -19}, },
            {{48, 83, -29}, {84, 84, 267}, {85, 122, -29}, },
            {},
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 83, -29}, {84, 84, 268}, {85, 122, -29}, },
            {{48, 122, -22}, },
            {{48, 104, -38}, {105, 105, 269}, {106, 122, 52}, },
            {{48, 115, -45}, {116, 116, 270}, {117, 122, 52}, },
            {},
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 115, -45}, {116, 116, 271}, {117, 122, 52}, },
            {{48, 66, -236}, {67, 67, 272}, {68, 122, -236}, },
            {{40, 40, 273}, {48, 122, -22}, },
            {{48, 68, -28}, {69, 69, 274}, {70, 122, -28}, },
            {{48, 98, -246}, {99, 99, 275}, {100, 122, 52}, },
            {{40, 40, 276}, {48, 122, -22}, },
            {{48, 100, -44}, {101, 101, 277}, {102, 122, 52}, },
            {{48, 57, 51}, {65, 65, 278}, {66, 122, -31}, },
            {{41, 41, 279}, },
            {{48, 67, -127}, {68, 68, 280}, {69, 122, -127}, },
            {{48, 95, -22}, {97, 97, 281}, {98, 122, 52}, },
            {{41, 41, 282}, },
            {{48, 99, -150}, {100, 100, 283}, {101, 122, 52}, },
            {{48, 75, -16}, {76, 76, 284}, {77, 122, -55}, },
            {},
            {{48, 122, -22}, },
            {{48, 107, -33}, {108, 108, 285}, {109, 122, 52}, },
            {},
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {35, 35, 35, 35, 35, 35, -1, 26, 27, 28, -1, 32, 1, 25, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 35, -1, -1, 34, 31, 31, 31, 29, 31, 31, 5, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 24, 31, 31, 31, 29, 31, 5, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 24, 31, 31, 30, -1, -1, -1, -1, -1, 34, 34, 34, 8, 31, 31, 31, 31, 31, 31, 31, 31, 19, 31, 17, 31, 10, 11, 31, 31, 31, 14, 31, 31, 15, 31, 8, 31, 31, 31, 31, 31, 31, 31, 31, 19, 31, 17, 31, 10, 11, 31, 31, 31, 14, 31, 31, 15, 31, -1, 33, 34, 31, 31, 16, 20, 31, 31, 31, 31, 22, 0, -1, -1, 31, 31, 31, -1, 31, 31, -1, 7, 31, 31, 16, 20, 31, 31, 31, 31, 22, 0, -1, -1, 31, 31, 31, -1, 31, 31, -1, 7, 31, 31, 31, 13, 31, 31, 10, 11, 31, 31, 31, 14, 21, 31, 15, 31, 31, 31, 13, 31, 31, 10, 11, 31, 31, 31, 14, 21, 31, 15, 31, 31, 31, -1, 23, 3, 31, 31, 18, 31, 31, 31, 31, -1, 23, 3, 31, 31, 18, 31, 9, 31, 31, 13, 2, 6, 31, 9, 31, 31, 13, 2, 6, 31, 31, 12, 31, 31, 12, 31, 31, -1, 31, 31, -1, 31, 31, 12, 4, 31, 12, 4, 2, 2, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
